# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Public Art Baltimore
tagline:          'Public Art and Monuments in Baltimore, Maryland.'
description:      'An informal working group of advocates, artists, historians and educators advocating for public art and historic monuments in Baltimore, Maryland.'
baseurl:          ""
url:              "http://publicartbaltimore.github.io/"

author:
  name:           'Baltimore Heritage'
  url:            https://twitter.com/bmoreheritage

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/publicartbaltimore/publicartbaltimore.github.io
